#!/usr/bin/env python
from __future__ import print_function
from draftin_a_flask import draftin_a_flask
print('Listening at endpoint', draftin_a_flask.app.secret_key)
draftin_a_flask.app.run('0.0.0.0', port=5678, debug=True)
